### ISSUE TITLE
Roadmap 🔥

### ISSUE THREAD

**Issue by leobittencourt** [leobittencourt/finances-backend#3]
### Clientes

Clientes pertencem a várias empresa e empresas possuem vários clientes

- [ ] Criar migration para clientes
- [ ] Criar seed de development para clientes
- [ ] Criar model para clientes
- [ ] Criar model hook para clientes
- [ ] Criar controller para clientes
- [ ] Criar filtro de pesquisas de clientes
- [ ] Criar tela de listagem de clientes
- [ ] Pesquisa de clientes
- [ ] Criar tela para adicionar novo cliente
- [ ] Criar tela para alterar cliente
- [ ] Exclusão de cliente

### Agenda

Uma empresa possui uma agenda e uma agenda pertence a apenas uma empresa

- [ ] Criar migration para agenda
- [ ] Criar seed de development para agenda
- [ ] Criar model para agenda
- [ ] Criar model hook para agenda
- [ ] Criar controller para agenda
- [ ] Criar filtro de pesquisas para agenda
- [ ] Criar componente de agenda
- [ ] Criar tela de agendamentos
- [ ] Pesquisa de agendamentos
- [ ] Criar tela para adicionar novo agendamento
- [ ] Criar tela para alterar agendamento
- [ ] Exclusão de agendamento

### Produtos

Empresas possuem vários produtos e produtos pertence a apenas uma empresa

- [ ] Criar migration para produtos
- [ ] Criar migration para estoque de produtos
- [ ] Criar seed de development para produtos
- [ ] Criar seed de development de estoque de produtos
- [ ] Criar model para produtos
- [ ] Criar model para estoque de produtos
- [ ] Criar model hook para produtos
- [ ] Criar model hook para estoque de produtos
- [ ] Criar controller para produtos
- [ ] Criar filtro de pesquisas de produtos
- [ ] Criar tela de listagem de produtos
- [ ] Criar tela de estoque de produtos
- [ ] Pesquisa de produtos
- [ ] Criar tela para adicionar novo produto
- [ ] Criar tela para alterar produto
- [ ] Exclusão de produto
- [ ] Criar relatório de estoques de produtos
